name: Locker - Lock stale issues and PRs, unlock reopened ones
on:
  schedule:
    - cron: '37 8 * * *' # Once per day, early morning PT

  workflow_dispatch:
    # Manual triggering through the GitHub UI, API, or CLI
    inputs:
      daysSinceClose:
        required: true
        default: "30"
      daysSinceUpdate:
        required: true
        default: "30"

  issues:
    types: [reopened]

  pull_request:
    types: [reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  lock:
    runs-on: ubuntu-latest
    # Only run the locking job for scheduled runs and manual dispatch, not for reopened events
    if: ${{ github.repository_owner == 'dotnet' && github.event_name != 'issues' && github.event_name != 'pull_request' }}
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v5
        with:
          repository: "microsoft/vscode-github-triage-actions"
          path: ./actions
          ref: 066bee9cefa6f0b4bf306040ff36fc7d96a6d56d # locker action commit sha
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Locker
        uses: ./actions/locker
        with:
          daysSinceClose:  ${{ fromJson(inputs.daysSinceClose  || 30) }}
          daysSinceUpdate: ${{ fromJson(inputs.daysSinceUpdate || 30) }}

  unlock:
    runs-on: ubuntu-latest
    # Only run the unlocking job when issues or PRs are reopened
    if: ${{ github.repository_owner == 'dotnet' && (github.event_name == 'issues' || github.event_name == 'pull_request') && github.event.action == 'reopened' }}
    steps:
      - name: Unlock reopened issue
        if: ${{ github.event_name == 'issues' }}
        run: |
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d '{"locked":false}'
      - name: Unlock reopened pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }} \
            -d '{"locked":false}'
